### ISSUE TITLE
Checkout Cart Feature

### ISSUE THREAD

**Issue by codingavatar** [FruitLoops-Hackreactor/fruitloops#79]
https://github.com/FruitLoops-Hackreactor/fruitloops/blob/276e1b95d430fd0c5afac3fc50ee3acb123f906e/src/components/ProductOverview/PO-Components/AddToCart.jsx#L47-L59
If you have extra time, you can actually add the items to the cart API. That way, if you were to implement a cart page, you can get the items added to your cart and display them there.

**Comment by quyencodes** [comment]
Thank you, Jessica. Will do. I imagine if it's a successful cart, it'll be in the `else if` block. I'll add that to the list.

**Comment by quyencodes** [comment]
Thank you, Jessica. Will do. I imagine if it's a successful cart, it'll be in the `else if` block. I'll add that to the list.
