### ISSUE TITLE
README

### ISSUE THREAD

**Issue by codingavatar** [FruitLoops-Hackreactor/fruitloops#83]
Flush out your ReadMe file when you're polishing your repo. I recommend having screen capture of each section of the website to embed in your ReadMe as gifs so that others can see your product without having to download and run the entire program. Some other ideas are [on Learn](https://learn-2.galvanize.com/cohorts/3484/blocks/94/content_files/Front%20End%20Capstone/exercises/writing_readmes.md).

**Comment by quyencodes** [comment]
Hi Jessica, we have our readme.md completed for our repo. Would love for you to take a look when you have time. Thank you.

**Comment by codingavatar** [comment]
Looks great! Love the github and LinkedIn links! You may want to name the project after your website or your group name, as opposed to "FEC Project", but that's totally up to you!
